# Generated by Django 4.2.3 on 2023-08-04 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Toyota", "Toyota"),
                            ("Honda", "Honda"),
                            ("Ford", "Ford"),
                            ("BMW", "BMW"),
                            ("Mercedes-Benz", "Mercedes-Benz"),
                            ("Audi", "Audi"),
                            ("Chevrolet", "Chevrolet"),
                            ("Volkswagen", "Volkswagen"),
                            ("Hyundai", "Hyundai"),
                            ("Nissan", "Nissan"),
                            ("Kia", "Kia"),
                            ("Volvo", "Volvo"),
                            ("Subaru", "Subaru"),
                            ("Mazda", "Mazda"),
                            ("Lexus", "Lexus"),
                            ("Tesla", "Tesla"),
                            ("Porsche", "Porsche"),
                            ("Jeep", "Jeep"),
                            ("Land Rover", "Land Rover"),
                            ("Ferrari", "Ferrari"),
                            ("Lamborghini", "Lamborghini"),
                            ("Maserati", "Maserati"),
                            ("Bentley", "Bentley"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issue_year", models.PositiveSmallIntegerField()),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("Hatchback", "Hatchback"),
                            ("Crossover", "Crossover"),
                            ("Coupe", "Coupe"),
                            ("Jeep", "Jeep"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "engine_capacity",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("engine_power", models.PositiveIntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Biodiesel", "Biodiesel"),
                            ("Propane", "Propane"),
                            ("Electricity", "Electricity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("Mechanical", "Mechanical"),
                            ("Automatic", "Automatic"),
                            ("Variator", "Variator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drive_unit",
                    models.CharField(
                        choices=[("Front", "Front"), ("Rear", "Rear"), ("All", "All")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "db_table": "cars",
                "ordering": ["-updated_at"],
            },
        ),
    ]
