version: '3'

services:
  django:
    container_name: django
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./car_showroom/.env
    volumes:
      - ./car_showroom:/app
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./car_showroom/.env
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./car_showroom/.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    container_name: celery
    build: .
    command: "celery -A car_showroom worker --loglevel=info"
    env_file:
      - ./car_showroom/.env
    volumes:
      - ./car_showroom:/app
    depends_on:
      - redis
    restart: always

  celery_beat:
    build:
      context: ./
    command: [ 'celery', '-A', 'car_showroom', 'beat' ]
    volumes:
      - ./car_showroom:/app
    depends_on:
      - redis
    env_file:
      - ./car_showroom/.env

  flower:
    container_name: flower
    build:
      context: .
    command: "celery -A car_showroom flower"
    volumes:
      - ./car_showroom:/app
    depends_on:
      - redis
      - celery
    env_file:
      - ./car_showroom/.env
    ports:
      - "5555:5555"

volumes:
  db:
  pgadmin: