# Generated by Django 4.2.3 on 2023-07-13 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('showroom_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.carmodel')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='provider.providermodel')),
            ],
            options={
                'verbose_name': 'SR_Car',
                'verbose_name_plural': 'SR_Cars',
                'db_table': 'sr_car',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('location', django_countries.fields.CountryField(default='US', max_length=2)),
                ('balance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('quantity_for_discount', models.PositiveSmallIntegerField(default=10)),
                ('car_list', models.ManyToManyField(through='showroom.ShowroomCar', to='common.carmodel')),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
                'db_table': 'showrooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.carmodel')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='provider.providermodel')),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='showroom.showroommodel')),
            ],
            options={
                'verbose_name': 'SR_Purchase',
                'verbose_name_plural': 'SR_Purchases',
                'db_table': 'sr_purchases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('car_list', models.ManyToManyField(to='common.carmodel')),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='showroom.showroommodel')),
            ],
            options={
                'verbose_name': 'SR_Discount',
                'verbose_name_plural': 'SR_Discounts',
                'db_table': 'sr_discounts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomCarCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_year', models.PositiveSmallIntegerField(default=2010)),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep')], max_length=20)),
                ('engine_capacity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('engine_power', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Biodiesel', 'Biodiesel'), ('Propane', 'Propane'), ('Electricity', 'Electricity')], max_length=20)),
                ('transmission', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automatic', 'Automatic'), ('Variator', 'Variator')], max_length=20)),
                ('drive_unit', models.CharField(choices=[('Front', 'Front'), ('Rear', 'Rear'), ('All', 'All')], max_length=20)),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='showroom.showroommodel')),
            ],
            options={
                'verbose_name': 'SR_Characteristic',
                'verbose_name_plural': 'SR_Characteristics',
                'db_table': 'sr_characteristics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='showroomcar',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='showroom.showroommodel'),
        ),
    ]
